### ISSUE TITLE
Seg. fault if args list ends with -c param (and config-file argument is missing)

### ISSUE THREAD

**Issue by FrancoisRegisDegott-eaton** [42ity/fty-example#21]
exec. ./fty-example -c /path/to/my/file
-> ok
exec. ./fty-example -c
-> generates a seg. fault

**Comment by jimklimov** [comment]
TODO : Build and verify if this is fixed so the issue can be closed :)

**Comment by FrancoisRegisDegott-eaton** [comment]
Fixed
